print('----------------------------GAPC TESTING------------------------------------------------')
for items in gapcObjectList:
    if items != 'NONE':
        print('--------------------')
        print(items.block)
        print(items.date)
        print(items.name)
        print(items.profitloss)
        print('rvalue ' + str(items.rvalue))
        print('gapclosepos ' + str(items.gapclosepos))
        print('gapcopenpos ' + str(items.gapcopenpos))
        print('tpvalue ' + str(items.tpvalue))
        print('slvalue ' + str(items.slvalue))
        print('tppos ' + str(items.tppos))
        print('slpos ' + str(items.slpos))
        print('gapclosetime ' + str(items.gapclosetime))
        print('gapcopentime ' + str(items.gapcopentime))
        print('takeprofittime ' + str(items.takeprofittime))
        print('Stoploss time' + items.stoplossstime)
        print('Comment ' + items.comment)
        print('--------------------')
print('----------------------------END------------------------------------------------')
print('----------------------------GAPC FIFTY------------------------------------------------')
for items in gapfiftyObjectList:
    if items != 'NONE':
        print('--------------------')
        print(items.block)
        print(items.date)
        print(items.name)
        print(items.profitloss)
        print('rvalue' + str(items.rvalue))
        print('fiftypercentvalue ' + str(items.fiftypercentvalue))
        print('fiftypercentpos ' + str(items.fiftypercentpos))
        print('gapopenvalue ' + str(items.gapopenvalue))
        print('tradeopenpos ' + str(items.tradeopenpos))
        print('slvalue ' + str(items.slvalue))
        print('tpvalue ' + str(items.tpvalue))
        print('SLPOS ' + str(items.slpos))
        print('tppos ' + str(items.tppos))
        print('gapfiftytptime ' + str(items.gapfiftytptime))
        print('gapFiftyOpenTime ' + str(items.gapFiftyOpenTime))
        print('halvehittime ' + str(items.halvehittime))
        print('stoplosstimstr ' + items.stoplosstimstr)
        print('comment ' + items.comment)
        print('--------------------')
print('----------------------------END------------------------------------------------')